import type { Quest } from '../types/quest.types'

export const PROGRAMMING_QUEST: Quest = {
    id: 'programming',
    title: 'Программистский квест',
    description: 'Проверь свои знания в программировании!',
    maxPoints: 100,
    questions: [
        {
            id: 'q1',
            text: 'Что такое TypeScript?',
            options: ['Язык программирования от Microsoft', 'Фреймворк для React', 'База данных', 'CSS препроцессор'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q2',
            text: 'Какой метод используется для добавления элемента в конец массива в JavaScript?',
            options: ['push()', 'pop()', 'shift()', 'unshift()'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q3',
            text: 'Что делает оператор "spread" (...) в JavaScript?',
            options: ['Разворачивает массив или объект', 'Умножает числа', 'Создает копию функции', 'Удаляет элементы'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q4',
            text: 'Что означает REST API?',
            options: ['Representational State Transfer', 'Remote Execution Service Tool', 'Reliable Encrypted Secure Transfer', 'Reactive State Protocol'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q5',
            text: 'Какой HTTP метод используется для получения данных?',
            options: ['GET', 'POST', 'PUT', 'DELETE'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q6',
            text: 'Что такое Promise в JavaScript?',
            options: ['Объект для работы с асинхронными операциями', 'Тип данных для хранения строк', 'Метод массива', 'Цикл'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q7',
            text: 'Что делает оператор === в JavaScript?',
            options: ['Строгое сравнение (тип и значение)', 'Присваивание', 'Нестрогое сравнение', 'Конкатенация'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q8',
            text: 'Что такое Git?',
            options: ['Система контроля версий', 'Язык программирования', 'База данных', 'Веб-сервер'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q9',
            text: 'Какая база данных является NoSQL?',
            options: ['MongoDB', 'PostgreSQL', 'MySQL', 'SQLite'],
            correctAnswer: 0,
            points: 10,
        },
        {
            id: 'q10',
            text: 'Что такое React?',
            options: ['JavaScript библиотека для UI', 'База данных', 'Язык программирования', 'Операционная система'],
            correctAnswer: 0,
            points: 10,
        },
    ],
}
