services:
  postgres:
    image: postgres:18-alpine
    container_name: telegram-quest-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_quest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
